version: "3"

services:
  books-api:
    build: ./
    environment:
      - MONGODB_DATABASE='mongodb+srv://vivek_sales_handy:joeyquark@cluster0.7oiq4.mongodb.net/books?authSource=admin&replicaSet=atlas-8lvchi-shard-0&w=majority&readPreference=primary&appname=MongoDB%20Compass&retryWrites=true&ssl=true'
    volumes:
      - './:/usr/src/app'
    ports:
      - 3000:3000


